# Generated by Django 4.2.5 on 2023-09-14 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_doctor_status_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Отзыв о центре медицинской диагностики')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать отзыв о клинике')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Отзыв клиента (пациента)',
                'verbose_name_plural': 'Отзывы клиентов (пациентов)',
            },
        ),
    ]
