# Generated by Django 4.2.5 on 2023-09-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(max_length=1500, verbose_name='Отзыв о центре медицинской диагностики'),
        ),
    ]
