# Generated by Django 4.2.5 on 2023-09-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_feedback_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время создания'),
        ),
    ]
